### ISSUE TITLE
Using Codefog Treepicker throws exception

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#107]
I want to use this widget: https://github.com/codefog/contao-widget_tree_picker in one of my extensions. After choosing some entries I get the following error:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message The magic setter is not supported anymore! thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Compatibility/DcCompat.php on line 109

#0 system/modules/widget_tree_picker/classes/TreePickerHelper.php(191): ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat->__set('field', 'category')
#1 system/modules/core/classes/Ajax.php(412): TreePicker\TreePickerHelper->executePostActions('reloadTreepicke...', Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#2 system/modules/core/classes/Ajax.php(194): Contao\Ajax->executePostActionsHook(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(256): Contao\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#7 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_postmanager_...', Array)
#8 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('postmanager')
#9 contao/main.php(20): Contao\BackendMain->run()
#10 {main}
```
I see the point for not using magic getters and setters but I think the DcCompat is for handling these widgets which are not fully compatible with the DcGeneral. Is there any possiblity to add the magic setters again?

**Comment by discordier** [comment]
As they are by definition a non op, I wonder what you want to achieve.
Adding support for setting properties which will never be evaluated seems useless and rather confusing instead of throwing an error as we currently do.
Can you explain why this should be fixed in dcg instead of using the dcg tree picker or changing the implementation of the codefog picker?

**Comment by discordier** [comment]
Having had a closer look at the implementation.
The codefog picker wants to override the property name which is plain wrong in context of dcg as then you would virtually exchange the rendered property with another one and therefore cause undefined behaviour.
You most definately want to give `DcGeneralTreePicker` a try.

**Comment by cboelter** [comment]
Oh I did not see, that there is a TreePicker in DcGeneral. Thanks for the Information. I think we close the ticket, because I see your points.
