### ISSUE TITLE
PageTree-Widget does not work correctly

### ISSUE THREAD

**Issue by cboelter** [contao-community-alliance/dc-general#110]
I've tested the PageTree-Widget with DcGeneral, after selecting pages I get the following error:

```
Warning: strpos() expects parameter 1 to be string, array given in system/modules/core/widgets/PageTree.php on line 105

#0 [internal function]: __error(2, 'strpos() expect...', '/Applications/M...', 105, Array)
#1 system/modules/core/widgets/PageTree.php(105): strpos(Array, ',')
#2 system/modules/core/library/Contao/Widget.php(798): Contao\PageTree->validator(Array)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(789): Contao\Widget->validate()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(73): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(231): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('category', 'tl_postmanager_...', '2')
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(242): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(246): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadPagetree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#11 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_postmanager_...', Array)
#12 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('postmanager')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}


Warning: explode() expects parameter 2 to be string, array given in system/modules/core/widgets/PageTree.php on line 111

#0 [internal function]: __error(2, 'explode() expec...', '/Applications/M...', 111, Array)
#1 system/modules/core/widgets/PageTree.php(111): explode(',', Array)
#2 system/modules/core/library/Contao/Widget.php(798): Contao\PageTree->validator(Array)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(789): Contao\Widget->validate()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(73): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(231): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('category', 'tl_postmanager_...', '2')
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(242): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(246): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadPagetree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#11 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_postmanager_...', Array)
#12 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('postmanager')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}


Warning: array_filter() expects parameter 1 to be array, null given in system/modules/core/widgets/PageTree.php on line 111

#0 [internal function]: __error(2, 'array_filter() ...', '/Applications/M...', 111, Array)
#1 system/modules/core/widgets/PageTree.php(111): array_filter(NULL)
#2 system/modules/core/library/Contao/Widget.php(798): Contao\PageTree->validator(Array)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(789): Contao\Widget->validate()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(73): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(231): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('category', 'tl_postmanager_...', '2')
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(242): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(246): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadPagetree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#11 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_postmanager_...', Array)
#12 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('postmanager')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}


Warning: array_map(): Argument #2 should be an array in system/modules/core/widgets/PageTree.php on line 111

#0 [internal function]: __error(2, 'array_map(): Ar...', '/Applications/M...', 111, Array)
#1 system/modules/core/widgets/PageTree.php(111): array_map('intval', NULL)
#2 system/modules/core/library/Contao/Widget.php(798): Contao\PageTree->validator(Array)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ContaoWidgetManager.php(789): Contao\Widget->validate()
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(73): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(231): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('category', 'tl_postmanager_...', '2')
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(242): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(246): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadPagetree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(466): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#9 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(128): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#10 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(84): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#11 system/modules/core/classes/Backend.php(393): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_postmanager_...', Array)
#12 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('postmanager')
#13 contao/main.php(20): Contao\BackendMain->run()
#14 {main}
```
It looks like the DcGeneral passes an array of values to the widget and the widget expects an comma separated string. I did not find any place, where I can fix it :(

**Comment by stefanheimes** [comment]
I change this. See a69951db92c66217f2d131186063d4b2fb9602cb

**Comment by discordier** [comment]
No feedback, closing therefore.
