### ISSUE TITLE
Definition properties is not registered in the configuration

### ISSUE THREAD

**Issue by psren** [contao-community-alliance/dc-general#111]
```php

Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Definition properties is not registered in the configuration mm_references. thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/DefaultContainer.php on line 140

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DataDefinition/DefaultContainer.php(201): ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer->getDefinition('properties')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(117): ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer->getPropertiesDefinition()
#2 composer/vendor/contao-community-alliance/dc-general/contao/backend/generaltree.php(32): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#3 {main}
```

If i open the rendersetting/form-settings and save without doing anything the error disappears.
I think this was an error during update, but I'm not sure.

**Comment by stefanheimes** [comment]
Change the handling with 3e57a00d33dee48eefee09da2a4650f58087330e .

**Comment by discordier** [comment]
No feedback, closing therefore.
