### ISSUE TITLE
Nach 'Dateibaum anpassung' Wurzelordner wählen (beim Klick auf Speichern)

### ISSUE THREAD

**Issue by MacKP** [contao-community-alliance/dc-general#14]
```php
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 140

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(162): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('')
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax3X.php(220): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree('file', Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/Ajax.php(246): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(891): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(94): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#5 system/modules/core/classes/Backend.php(259): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_at...', Array)
#6 contao/main.php(136): Contao\Backend->getBackendModule('metamodels')
#7 contao/main.php(287): Main->run()
#8 {main}
```

**Comment by xantippe** [comment]
getestet MM 2.0.0a9 DCG 2.0.0b33

keine Fehlermeldung

kann m.E. geschlossen werden
