### ISSUE TITLE
 vsprintf(): Too few arguments in TreePicker.php

### ISSUE THREAD

**Issue by psren** [contao-community-alliance/dc-general#144]
```
Warning: vsprintf(): Too few arguments in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php on line 937
#0 [internal function]: __error(2, 'vsprintf(): Too...', '/kunden/302047_...', 937, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(937): vsprintf('
#0 [internal function]: __error(2, 'vsprintf(): Too...', '/kunden/302047_...', 937, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(937): vsprintf('
#0 [internal function]: __error(2, 'vsprintf(): Too...', '/kunden/302047_...', 937, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(937): vsprintf('
#0 [internal function]: __error(2, 'vsprintf(): Too...', '/kunden/302047_...', 937, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(937): vsprintf('
#0 [internal function]: __error(2, 'Cannot modify h...', '/kunden/302047_...', 294, Array)
#1 system/modules/core/library/Contao/Template.php(294): header('Vary: User-Agen...', false)
#2 system/modules/core/classes/BackendTemplate.php(153): Contao\Template->output()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(160): Contao\BackendTemplate->output()
#4 composer/vendor/contao-community-alliance/dc-general/contao/backend/generaltree.php(32): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#5 {main}

Warning: Cannot modify header information - headers already sent by (output started at /kunden/302047_70174/kunden/reich/system/helper/functions.php:68) in system/modules/core/library/Contao/Template.php on line 295
#0 [internal function]: __error(2, 'Cannot modify h...', '/kunden/302047_...', 295, Array)
#1 system/modules/core/library/Contao/Template.php(295): header('Content-Type: t...')
#2 system/modules/core/classes/BackendTemplate.php(153): Contao\Template->output()
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(160): Contao\BackendTemplate->output()
#4 composer/vendor/contao-community-alliance/dc-general/contao/backend/generaltree.php(32): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#5 {main}
```

![bildschirmfoto 2015-07-13 um 10 19 54 2](https://cloud.githubusercontent.com/assets/1016798/8645565/cc8d5fb6-2948-11e5-8ec6-1a075b616517.png)

**Comment by psren** [comment]
![bildschirmfoto 2015-07-13 um 10 30 44](https://cloud.githubusercontent.com/assets/1016798/8645737/4047f744-294a-11e5-8f8e-e4dbf67e74b9.png)

**Comment by discordier** [comment]
Ia am unable to reproduce this. I have configured my attribute exactly like this and configured the input screen to consist of a picker.

**Comment by discordier** [comment]
@psren Can you shed any further light on how to reproduce the problem?

**Comment by psren** [comment]
yes, will try it on monday.

**Comment by discordier** [comment]
Ok, monday... but which year and which month? :)

**Comment by psren** [comment]
Hahah, totally forgot that. Moment please

**Comment by psren** [comment]
Works as expected in newer versions.

**Comment by zonky2** [comment]
We have the bug still... look at https://github.com/MetaModels/core/issues/805

the problem at tl_page is the URL at label - the URL is encoded and can be have any percent signs e.g. ```?do=metamodel_mm_mitarbeiterliste&table=mm_mitarbeiterliste&field=my_pages&act=show&id=mm_mitarbeiterliste%3A%3A6&value=...``` at the string ```$event->getLabel()```

look at https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php#L994

I can fix the bug with a small hotfix like

```diff
            if (!is_array($event->getArgs())) {
                $string = $event->getArgs();
            } else {
-                $string = vsprintf($event->getLabel(), $event->getArgs());
+                $string = vsprintf(urldecode($event->getLabel()), $event->getArgs());
            }
```

![shot204](https://cloud.githubusercontent.com/assets/1045318/15172980/9478e23a-1759-11e6-95d9-941a3b0a213a.jpg)

may be we can compare the count of percent signs in $event->getLabel() with the count of array values..?

**Comment by discordier** [comment]
No, the label must be properly provided. There is a bug in the label generating code

**Comment by zonky2** [comment]
o.k. - at the ```setLabel```?
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Event/ModelToLabelEvent.php#L91-L96

**Comment by zonky2** [comment]
fixed https://github.com/MetaModels/core/issues/805#issuecomment-289989811
