### ISSUE TITLE
Error bei Zuweisung als Kindtabelle in MM zu bestimmten Contao-Tabellen

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#179]
Error bei Zuweisung als Kindtabelle in MM zu bestimmten Contao-Tabellen

**Events: tl_calendar_events**

URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=calendar&id=3&table=mm_filter&pid=tl_calendar_events::9&rt=cb2a4221850095a6a10a275098497ed1&ref=96ad780d```

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '3' thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 116

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(77): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('3')
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(57): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(380): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->showAll()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('calendar')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```

**Events: tl_calendar**
URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=calendar&table=mm_filter&act=create&pid=tl_calendar::3&rt=cb2a4221850095a6a10a275098497ed1&ref=a52ab298```
=> o.k.

**News: tl_news**
URL: ```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=news&id=1&table=mm_filter&pid=tl_news::7&rt=cb2a4221850095a6a10a275098497ed1&ref=288b2dc0```

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '1' thrown in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 116

#0 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(77): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('1')
#1 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter.php(57): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->checkLanguage(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Filter\LanguageFilter->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#5 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC_General.php(380): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#8 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\classes\Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->showAll()
#9 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('news')
#10 C:\Contao2Go\htdocs\vhosts\contao-3.5.x\contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```

**News: tl_news_archive**
```http://localhost:4001/vhosts/contao-3.5.x/contao/main.php?do=news&table=mm_filter&pid=tl_news_archive::1&rt=cb2a4221850095a6a10a275098497ed1&ref=53851300```
=> o.k.

**Comment by discordier** [comment]
Ist vermutlich ein Bug im MM core, die operation button URLs werden falsch generiert.

**Comment by xantippe** [comment]
Ticket im Core machen?

**Comment by discordier** [comment]
Yop, ist ein bug im MM core. Please move.

**Comment by discordier** [comment]
Reopened contao-community-alliance/dc-general#68

**Comment by discordier** [comment]
And closed again, should definately be moved to MetaModels/core.
@xantippe would you please be so kind?

**Comment by xantippe** [comment]
ich kann z.Z. keine neuen Issues anlegen..?!? "Submit" ist disabled - Kommentieren geht weiterhin...

**Comment by xantippe** [comment]
erledigt...

**Comment by discordier** [comment]
Please link the issues after moving.

**Comment by xantippe** [comment]
https://github.com/MetaModels/core/issues/996

**Comment by zonky2** [comment]
is fixed with https://github.com/MetaModels/core/commit/9cdae2068ecb41cfd6c38119a276cc048e926c59

we can close it...
