### ISSUE TITLE
Paste in Mode 4 causes save of empty dataset without clicking "save".

### ISSUE THREAD

**Issue by xantippe** [contao-community-alliance/dc-general#183]
öffnet man die Eingabemaske für ein MM ohne speichern zu klicken, kommt anschließend die Fehlermeldung

```
Fatal error: Uncaught exception Exception with message Query error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1 (SELECT count(*) AS itemCount FROM) thrown in system\modules\core\library\Contao\Database\Statement.php on line 295

#0 system\modules\core\library\Contao\Database\Statement.php(264): Contao\Database\Statement->query()
#1 composer\vendor\metamodels\core\src\MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber.php(182): Contao\Database\Statement->execute()
#2 [internal function]: MetaModels\DcGeneral\Events\Table\MetaModels\Subscriber->modelToLabel(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber.php(89): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ModelToLabelEvent))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FormatModelLabelSubscriber->handleFormatModelLabel(Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(243): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\FormatModelLabelEvent))
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(264): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->setListViewLabel(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), Array)
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView.php(324): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->viewList(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(141): call_user_func_array(Array, Array)
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#20 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#21 contao\main.php(20): Contao\BackendMain->run()
#22 {main}
```

in der Tabelle tl_metamodel wird ein neuer Datensatz aber ohne "name" und "tabelName" angelegt - den Datensatz muss man per phpMyAdmin löschen...

**Comment by discordier** [comment]
Stack trace by @baumannsven how the save method is triggered before saving:
```
#0 dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1060): Contao\Doctrine\ORM\DataContainer\General\EntityDataProvider->saveEach(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection))
#1 dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(940): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'sorting', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer))
#2 dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(769): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Array)
#3 dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(647): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Array)
#4 dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(424): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#6 dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(141): call_user_func_array(Array, Array)
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#8 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(284): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 dc-general/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(380): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#13 system/modules/core/classes/Backend.php(650): ContaoCommunityAlliance\DcGeneral\DC_General->showAll()
#14 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('avisota_newslet...')
#15 contao/main.php(20): Contao\BackendMain->run()
#16 {main}
```

**Comment by xantippe** [comment]
sorry wg. "Doppelposting" https://github.com/MetaModels/core/issues/946

**Comment by xantippe** [comment]
kommt mit beta34 nicht mehr vor
