### ISSUE TITLE
Warning: array_key_exists() expects parameter 2 to be array, null given in  .../EditMask.php on line 779

### ISSUE THREAD

**Issue by felixxxxx** [contao-community-alliance/dc-general#185]
Ich habe gerade mm auf die neueste Version manuel upgedate. 
Jetzt erhalte ich im Backend folgenden Fehler:

```
Warning: array_key_exists() expects parameter 2 to be array, null given in C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php on line 779

#0 [internal function]: __error(2, 'array_key_exist...', 'C:\\xampp\\htdocs...', 779, Array)
#1 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(779): array_key_exists('tl_metamodel_dc...', NULL)
#2 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(402): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->getLegendStates()
#3 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(682): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->buildFieldSet(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Palette\Palette), NULL)
#4 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(602): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#5 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(577): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(141): call_user_func_array(Array, Array)
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 C:\xampp\htdocs\ingrada\system\modules\symfony-event-dispatcher\classes\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 C:\xampp\htdocs\ingrada\system\modules\symfony-event-dispatcher\classes\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 C:\xampp\htdocs\ingrada\system\modules\dc-general\classes\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 C:\xampp\htdocs\ingrada\system\modules\metamodels\classes\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 C:\xampp\htdocs\ingrada\system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#14 C:\xampp\htdocs\ingrada\system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#15 C:\xampp\htdocs\ingrada\contao\main.php(20): Contao\BackendMain->run()
#16 {main}

```

**Comment by stefanheimes** [comment]
Im Branch hotfix/2.0.0-beta34 behoben. Jedenfalls sehe ich den Fehler hier nicht mehr.

**Comment by xantippe** [comment]
kann ich gestätigen
