### ISSUE TITLE
MM: Error bei Einfügen Filterregel an "0. Stelle"

### ISSUE THREAD

**Issue by xantippe** [contao-community-alliance/dc-general#188]
will man die erste Filterregel einfügen bzw. an "0. Stelle", kommt nach "pasteinto.0" die u.g. Fehlermeldung.

Die Filterregel wird dennoch angelegt und kann anschließend weiter bearbeitet werden.

DCG beta34
MM alpha10

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Can't instantiate model id. No model id given. thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php on line 62

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php(92): ContaoCommunityAlliance\DcGeneral\Data\ModelId->__construct('tl_metamodel_fi...', '0')
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Data\ModelId.php(126): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromValues('tl_metamodel_fi...', '0')
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener.php(80): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized('tl_metamodel_fi...')
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener.php(55): ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener->handleInto(Object(ContaoCommunityAlliance\DcGeneral\Contao\InputProvider), Object(ContaoCommunityAlliance\DcGeneral\Controller\DefaultController), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#4 [internal function]: ContaoCommunityAlliance\DcGeneral\EventListener\ModelRelationship\TreeEnforcingListener->process(Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(668): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\EnforceModelRelationshipEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(602): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(577): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), NULL, NULL)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(141): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(181): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#18 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#19 contao\main.php(20): Contao\BackendMain->run()
#20 {main}
```

**Comment by xantippe** [comment]
gleiche verhalten bei Einfügen Ansichtsbedingung an Stelle "0"

**Comment by xantippe** [comment]
mit PR #195 gefixt
