### ISSUE TITLE
Copy in MM get error e.g copy of render settings or input mask

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#278]
C 3.5.14
MM a12
DCG b36

same error at render setting as input mask:
```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber::handlePostPersistModelEvent() must be an instance of ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent, instance of ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent given in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php on line 65

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php(65): __error(4096, 'Argument 1 pass...', 'C:\\Contao2Go\\ht...', 65, Array)
#1 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber->handlePostPersistModelEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler.php(112): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler.php(168): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler->copy(Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler->process()
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler.php(71): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#14 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#15 contao\main.php(20): Contao\BackendMain->run()
#16 {main}
```

look at https://github.com/MetaModels/core/issues/811

at filter rule
```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber::handlePostPersistModelEvent() must be an instance of ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent, instance of ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent given in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php on line 65

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber.php(65): __error(4096, 'Argument 1 pass...', 'C:\\Contao2Go\\ht...', 65, Array)
#1 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber->handlePostPersistModelEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(844): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(799): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doCloneAction(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(752): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyAction(Array, Array, Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(638): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), Array)
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(423): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView.php(523): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(140): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#17 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#18 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#19 contao\main.php(20): Contao\BackendMain->run()
#20 {main}
```

copy Item

```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber::handlePostPersistModelEvent() must be an instance of ContaoCommunityAlliance\DcGeneral\Event\PostPersistModelEvent, instance of ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent given in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php on line 65

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FallbackResetSubscriber.php(65): __error(4096, 'Argument 1 pass...', 'co...', 65, Array)
#1 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Subscriber\FallbackResetSubscriber->handlePostPersistModelEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent), 'dc-general.mode...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php(112): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.mode...', Object(ContaoCommunityAlliance\DcGeneral\Event\PostDuplicateModelEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ActionHandler/CopyHandler.php(168): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler->copy(Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CopyHandler->process()
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/View/ActionHandler/AbstractEnvironmentAwareHandler.php(71): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractEnvironmentAwareHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(130): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#14 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_xx...')
#15 contao/main.php(20): Contao\BackendMain->run()
#16 {main}
```

**Comment by zonky2** [comment]
o.k. the error is fixed and we can copy .. but the copy of render settings or settings of input mask copy only the "parent settings" without the attributes => is this an bug or "feature"?

**Comment by discordier** [comment]
Are you talking about the "deep-copy" feature?

**Comment by zonky2** [comment]
yes... deep copy

**Comment by zonky2** [comment]
I have the third error - see at first posting - if I copy a Item. but the copy works
