### ISSUE TITLE
Error at sorting with Ajax (MetaModels)

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#306]
If we activate manual sorting and sort per Ajax we have the follow error at console

```
Fatal error: Uncaught exception RuntimeException with message No models passed to pasteAfter(). thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 1075

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(929): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteAfter(Object(MetaModels\DcGeneral\Data\Model), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'sorting')
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(772): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId), NULL, NULL, Array)
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(651): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId), NULL, NULL, Array)
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, Object(ContaoCommunityAlliance\DcGeneral\Data\ModelId), NULL, NULL, NULL, Array)
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler->process()
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#10 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#11 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#12 contao\main.php(20): Contao\BackendMain->run()
#13 {main}
```

Forum: https://community.contao.org/de/showthread.php?63844-Nach-Update-funktioniert-manuelle-Sortierung-nicht-mehr&p=418910#post418910

Ajax works with DCG beta36 but send error with beta38

**Comment by zonky2** [comment]
fixed with #313
