### ISSUE TITLE
MM Grouping and Sorting: error by click at "editheader" 

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#310]
MM core alpha14
DCG beta38

![shot280](https://cloud.githubusercontent.com/assets/1045318/18835354/00f110f0-83fb-11e6-9404-d62e75d24bc4.jpg)

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Data/ModelId.php on line 116

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(163): ContaoCommunityAlliance\DcGeneral\Data\ModelId::fromSerialized(NULL)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/BaseConfigRegistry.php(185): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->buildBaseConfig(NULL)
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Event/Subscriber.php(330): ContaoCommunityAlliance\DcGeneral\BaseConfigRegistry->getBaseConfig()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\Event\Subscriber->initializePanels(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(131): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system/modules/core/classes/Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 system/modules/core/controllers/BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#10 contao/main.php(20): Contao\BackendMain->run()
#11 {main}
```

**Comment by zonky2** [comment]
=> MM bug
