### ISSUE TITLE
Data manipulation permissions / Berechtigungen zur Datenanpassung

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#322]
add data manipulation permissions and hide the icons and check the url request

don't forget to check editAll and overrideAll

more see at https://github.com/MetaModels/core/issues/865

**Comment by discordier** [comment]
wut?

**Comment by zonky2** [comment]
@baumannsven have alles in the griff

**Comment by discordier** [comment]
Branch has been merged in ba3e4fe3174b89b966d35511dfdce2c1a6bb0d84. Is there anything missing or can we close this?

**Comment by zonky2** [comment]
Bug is currenty open - I checked the issue with DCG b39 and MM core a15 https://github.com/MetaModels/core/issues/865#issuecomment-167541022

**Comment by discordier** [comment]
Ehm, you checked this on Dec 28, 2015 but I only merged it on Mar 7, 2017. So I guess this needs a recheck?

**Comment by zonky2** [comment]
pls look at tooltip "edited" - `edited 5 day ago` (31.03.2017)

**Comment by zonky2** [comment]
@baumannsven pls set a reference from PR or Branch to ticket...
I tested https://github.com/contao-community-alliance/dc-general/tree/hotfix/check_permission_disable_model_commands

I disable all checkboxes: I see only the "i icon"

check "allow create": 
* add new: works fine
* copy:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_mitarbeiterliste is not editable thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php on line 184

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(697): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->checkEditable(Object(MetaModels\DcGeneral\Data\Model))
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#10 contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```
but ad a new item!

check delete item:
I see the red cross... ans I cann delete a item

check edit item:
I see the pencil and can dédit the item... and copy them and delete them

**Comment by zonky2** [comment]
Q: should `copy` allow at "allow create" or not?

**Comment by zonky2** [comment]
@baumannsven note: thjink about the buttons on editAll

**Comment by zonky2** [comment]
check after update: https://github.com/contao-community-alliance/dc-general/commit/e008e1fae2975b15a56852576fd93d99eecbb340

all status works fine!

only one... if we see the pencil but the permission to edit is not allowed, we see

```` 
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message DataContainer mm_mitarbeiterliste is not editable thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php on line 184

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(697): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->checkEditable(Object(MetaModels\DcGeneral\Data\Model))
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler.php(76): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\EditHandler->process()
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#7 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#9 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodel_mm_mi...')
#10 contao\main.php(20): Contao\BackendMain->run()
#11 {main}
```
at all other we see a backend message "Error"

**Comment by baumannsven** [comment]
@zonky if admin change permission the user has on the fly the right  permission.

**Comment by zonky2** [comment]
@baumannsven works perfect!

@discordier RTM
https://github.com/contao-community-alliance/dc-general/tree/hotfix/check_permission_disable_model_commands

**Comment by zonky2** [comment]
last test with commit 46d8181 => works fine!

@discordier RTM

**Comment by zonky2** [comment]
merged
