### ISSUE TITLE
Error at hotfix/beta-39  (c90704fb)

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#323]
* contao-community-alliance/dc-general 	dev-hotfix/beta-39 (c90704fb)
* metamodels/core 	dev-hotfix/alpha-15 (94cf9fab)

at all icons in be, we have:
```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Data provider tl_metamodel not defined thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DefaultEnvironment.php on line 294

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector.php(124): ContaoCommunityAlliance\DcGeneral\DefaultEnvironment->getDataProvider('tl_metamodel')
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(133): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->__construct(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\HardCodedPopulator.php(60): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->setEnvironment(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\HardCodedPopulator.php(89): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\HardCodedPopulator->populateController(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\EnvironmentPopulator\AbstractEventDrivenEnvironmentPopulator.php(53): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Populator\HardCodedPopulator->populate(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment))
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\EnvironmentPopulator\AbstractEventDrivenEnvironmentPopulator->process(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(351): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\PopulateEnvironmentEvent))
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(298): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(80): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#11 system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_at...', Array)
#12 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#13 contao\main.php(20): Contao\BackendMain->run()
#14 {main}
```

and in addition to attribute:
```
Warning: array_merge_recursive(): Argument #2 is not an array in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php on line 437

#0 [internal function]: __error(2, 'array_merge_rec...', 'C:\\Contao2Go\\ht...', 437, Array)
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(437): array_merge_recursive(Array, NULL)
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(477): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->parseParentChildConditions(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultModelRelationshipDefinition))
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(68): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->parseConditions(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder.php(96): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->build(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer), Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder->process(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(392): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(336): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createContainer()
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(298): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(80): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#12 system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_at...', Array)
#13 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#14 contao\main.php(20): Contao\BackendMain->run()
#15 {main}
```

**Comment by zonky2** [comment]
@baumannsven send me a solution

at https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Populator/HardCodedPopulator.php#L40

```
-    const PRIORITY = 1000;
+    const PRIORITY = 50;
```
set lower than 
https://github.com/contao-community-alliance/dc-general/blob/master/src/ContaoCommunityAlliance/DcGeneral/Contao/Dca/Populator/DataProviderPopulator.php#L37

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/commit/f1720df3b9ee141cfa644292676e5dfbf8130ed8

**Comment by zonky2** [comment]
update to DCG dev-hotfix/beta-39 (755d8c3b)

if I click at icon:

```
Warning: array_merge_recursive(): Argument #2 is not an array in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php on line 437

#0 [internal function]: __error(2, 'array_merge_rec...', 'C:\\Contao2Go\\ht...', 437, Array)
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(437): array_merge_recursive(Array, NULL)
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(477): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->parseParentChildConditions(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\DefaultModelRelationshipDefinition))
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder.php(68): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->parseConditions(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer))
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder.php(96): ContaoCommunityAlliance\DcGeneral\Contao\Dca\Builder\Legacy\ExtendedLegacyDcaDataDefinitionBuilder->build(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\DefaultContainer), Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\DataDefinition\Builder\AbstractEventDrivenDataDefinitionBuilder->process(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(392): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\BuildDataDefinitionEvent))
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(336): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createContainer()
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory.php(298): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createEnvironment()
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(80): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#12 system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_at...', Array)
#13 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#14 contao\main.php(20): Contao\BackendMain->run()
#15 {main}
```

if I add a new attribute,  at save

```
Fatal error: Call to a member function getProviderName() on null in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php on line 946
```

**Comment by discordier** [comment]
I still can not reproduce this.
However, the line this occurs in checks the parent model of the current model.
Apparently this can not be determined in your installation and therefore we will have to check the model collector then why none is to be found.
Can you trace into the model collector?

**Comment by zonky2** [comment]
this https://github.com/MetaModels/core/pull/1069 fixed the 

```
Warning: array_merge_recursive(): ...
```
