### ISSUE TITLE
Error at ModelCollector.php with DCG dev-hotfix/beta-39 (f52d2653) add save view condition

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#324]
at save a new view condition, we have

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralInvalidArgumentException with message Invalid condition, root models can not have parents! thrown in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector.php on line 361

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector.php(204): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->searchParentOfInHierarchical(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector.php(393): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->searchParentOf(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector.php(234): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->addParentFilter(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultConfig))
#3 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(915): ContaoCommunityAlliance\DcGeneral\Controller\ModelCollector->collectSiblingsOf(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), 'sorting', NULL)
#4 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(617): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), 'sorting')
#5 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask.php(725): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->doPersist()
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CreateHandler.php(81): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\CreateHandler->process()
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(146): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler.php(64): ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->callAction('create')
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler.php(54): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ActionHandler\PasteHandler->process()
#14 [internal function]: ContaoCommunityAlliance\DcGeneral\View\ActionHandler\AbstractHandler->handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#15 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#16 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\DefaultController.php(152): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#18 composer\vendor\metamodels\core\src\MetaModels\BackendIntegration\Module.php(74): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 system\modules\core\classes\Backend.php(423): MetaModels\BackendIntegration\Module->generate()
#20 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#21 contao\main.php(20): Contao\BackendMain->run()
#22 {main}
```

at the https://github.com/contao-community-alliance/dc-general/blob/hotfix/beta-39/src/ContaoCommunityAlliance/DcGeneral/Controller/ModelCollector.php#L357 $model is

```
ContaoCommunityAlliance\DcGeneral\Data\DefaultModel Object
(
    [arrProperties:protected] => Array
        (
            [pid] => 0
            [settingId] => 3
            [type] => conditionpropertyvalueis
            [enabled] => 1
            [comment] => 
            [attr_id] => 10
            [value] => 1
        )

    [mixID:protected] => 
    [strProviderName:protected] => tl_metamodel_dcasetting_condition
    [arrMetaInformation:protected] => Array
        (
            [isChanged] => 1
        )

)
```

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/commit/a588855931c2a622a4149181dfb1f9ed969a4511 and works fine
