### ISSUE TITLE
error add/change file with filepicker with beta 39 (f52d2653)

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#325]
with DCG dev-hotfix/beta-39 (f52d2653)

```
Backend-Icon

Recoverable error: Argument 4 passed to ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ManipulateWidgetEvent::__construct() must be an instance of Widget, instance of ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Widget\FileTree given, called in C:\Contao2Go\htdocs\vhosts\contao-3.5.x\composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder.php on line 454 and defined in composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ManipulateWidgetEvent.php on line 72

#0 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ManipulateWidgetEvent.php(72): __error(4096, 'Argument 4 pass...', 'C:\\Contao2Go\\ht...', 72, Array)
#1 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder.php(454): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\ManipulateWidgetEvent->__construct(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel), Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\Properties\DefaultProperty), Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Widget\FileTree))
#2 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder.php(87): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder->buildWidget(Object(ContaoCommunityAlliance\DcGeneral\DataDefinition\Definition\Properties\DefaultProperty), Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultModel))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Subscriber\WidgetBuilder::handleEvent(Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(184): call_user_func('ContaoCommunity...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent), 'dc-general.view...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#5 composer\vendor\symfony\event-dispatcher\EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#6 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager.php(242): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view...', Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Event\BuildWidgetEvent))
#7 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager.php(409): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->getWidget('backendicon', Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#8 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X.php(80): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ContaoWidgetManager->processInput(Object(ContaoCommunityAlliance\DcGeneral\Data\PropertyValueBag))
#9 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X.php(237): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->getWidget('backendicon', 'tl_metamodel_dc...', 'files/metamodel...')
#10 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X.php(256): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadTree()
#11 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Controller\Ajax.php(228): ContaoCommunityAlliance\DcGeneral\Controller\Ajax3X->reloadFiletree(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#12 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView.php(381): ContaoCommunityAlliance\DcGeneral\Controller\Ajax->executePostActions(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#13 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(149): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAjaxCall()
#14 composer\vendor\contao-community-alliance\dc-general\src\ContaoCommunityAlliance\DcGeneral\DC\General.php(92): ContaoCommunityAlliance\DcGeneral\DC_General->checkAjaxCall()
#15 system\modules\core\classes\Backend.php(408): ContaoCommunityAlliance\DcGeneral\DC_General->__construct('tl_metamodel_dc...', Array)
#16 system\modules\core\controllers\BackendMain.php(131): Contao\Backend->getBackendModule('metamodels')
#17 contao\main.php(20): Contao\BackendMain->run()
#18 {main}
```

but to save is possible

**Comment by discordier** [comment]
I think we need to `class_alias` some classes to the root namespace now as we are moving away from the global namespace to allow Contao to keep track of the correct classes.

**Comment by zonky2** [comment]
fixed with https://github.com/contao-community-alliance/dc-general/pull/327
