### ISSUE TITLE
BE, Suche aktiviert, mit FeldTyp "Text" und "tags"

### ISSUE THREAD

**Issue by tim-bec** [contao-community-alliance/dc-general#41]
Original: https://github.com/MetaModels/DC_General/issues/132

```
Warning: Illegal offset type in composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php on line 159

#0 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php(159): __error(2, 'Illegal offset ...', '/var/www/client...', 159, Array)
#1 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Panel/DefaultPanel.php(71): DcGeneral\Panel\DefaultFilterElement->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#2 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Panel/DefaultPanelContainer.php(70): DcGeneral\Panel\DefaultPanel->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#3 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1279): DcGeneral\Panel\DefaultPanelContainer->initialize(Object(DcGeneral\Data\DefaultConfig))
#4 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1294): DcGeneral\Controller\DefaultController->buildPanel()
#5 composer/vendor/metamodels/dc_general/system/modules/generalDriver/DcGeneral/DC_General.php(2382): DcGeneral\Controller\DefaultController->showAll()
#6 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(176): DcGeneral\DC_General->showAll()
#7 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(196): MetaModels\BackendIntegration\Module->runDC()
#8 composer/vendor/metamodels/core/src/system/modules/metamodels/MetaModels/BackendIntegration/Module.php(210): MetaModels\BackendIntegration\Module->performNormal()
#9 system/modules/core/classes/Backend.php(271): MetaModels\BackendIntegration\Module->generate()
#10 contao/main.php(136): Contao\Backend->getBackendModule('metamodel_mm_bu...')
#11 contao/main.php(287): Main->run()
#12 {main}
````

# blackbee
Ich kann ebenfalls das Problem bestätigen.

Bei mir tritt das Problem in folgender Konstellation auf, wenn ich die Filterung für "Translated Tags" aktiviere.

Ich habe mir mal in Zeile 159 in der Datei DefaultFilterElement.php aus der foreach-Schleife das $objOption mittels print_r ausgeben lassen.

Dort ist zu sehen, dass das Element überhaupt keine Einträge aus den Tags anzeigt.

Wahrscheinlich liegt ein Defekt in der Übergabe aus dem MetaModels vor.

Kann das jemand von Euch überprüfen?

# pandroid

Ich kann das auch bestätigen.
So bald ich das Attribut mit dem Feldtyp "tags" mit "Filterbar" markiere, erhalte ich beim Aufruf der Backend-Liste den Fehler
```
Warning: Illegal offset type in system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php on line 159
#0 system/modules/generalDriver/DcGeneral/Panel/DefaultFilterElement.php(159): __error(2, 'Illegal offset ...', '/www/htdocs/w00...', 159, Array)
#1 system/modules/generalDriver/DcGeneral/Panel/DefaultPanel.php(71): DcGeneral\Panel\DefaultFilterElement->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#2 system/modules/generalDriver/DcGeneral/Panel/DefaultPanelContainer.php(70): DcGeneral\Panel\DefaultPanel->initialize(Object(DcGeneral\Data\DefaultConfig), NULL)
#3 system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1279): DcGeneral\Panel\DefaultPanelContainer->initialize(Object(DcGeneral\Data\DefaultConfig))
#4 system/modules/generalDriver/DcGeneral/Controller/DefaultController.php(1294): DcGeneral\Controller\DefaultController->buildPanel()
#5 system/modules/generalDriver/DcGeneral/DC_General.php(2382): DcGeneral\Controller\DefaultController->showAll()
#6 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(176): DcGeneral\DC_General->showAll()
#7 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(196): MetaModels\BackendIntegration\Module->runDC()
#8 system/modules/metamodels/MetaModels/BackendIntegration/Module.php(210): MetaModels\BackendIntegration\Module->performNormal()
#9 system/modules/core/classes/Backend.php(272): MetaModels\BackendIntegration\Module->generate()
#10 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_sh...')
#11 contao/main.php(293): Main->run()
#12 {main}
```

**Comment by xantippe** [comment]
Suche und Filtern von [tags] kann aktiviert werden ohne Fehlermeldung
