### ISSUE TITLE
[2.0] Error on PagePicker before save item

### ISSUE THREAD

**Issue by zonky2** [contao-community-alliance/dc-general#435]
Error on PagePicker before save item

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Execute callback tl_page_canonical::switchPalette failed - Exception message: Unparsable encoded id value: '' thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/Callbacks.php on line 79

#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Callback/AbstractCallbackListener.php(117): ContaoCommunityAlliance\DcGeneral\Contao\Callback\Callbacks::callArgs(Array, Array)
#1 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(184): ContaoCommunityAlliance\DcGeneral\Contao\Callback\AbstractCallbackListener->__invoke(Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent), 'dc-general.fact...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 composer/vendor/symfony/event-dispatcher/EventDispatcher.php(46): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent))
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Factory/DcGeneralFactory.php(310): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.fact...', Object(ContaoCommunityAlliance\DcGeneral\Factory\Event\CreateDcGeneralEvent))
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(234): ContaoCommunityAlliance\DcGeneral\Factory\DcGeneralFactory->createDcGeneral()
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreePicker.php(191): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->setUp(Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeSelect.php(147): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreePicker->__construct(Array, Object(ContaoCommunityAlliance\DcGeneral\Contao\Compatibility\DcCompat))
#7 system/modules/dc-general/backend/generaltree.php(41): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeSelect->run()
#8 {main}
```

**Comment by baumannsven** [comment]
Fixed in ff8735c2d21fcc70cce35204b1b4615c7e94f4e6
