### ISSUE TITLE
Error bei Anlegen eines Datensatzes bei MM als Kindtabelle

### ISSUE THREAD

**Issue by xantippe** [contao-community-alliance/dc-general#68]
unter TNG NB 27.08. + https://github.com/contao-community-alliance/dc-general/commit/6281e73de03dd792e5644caa3106eba04591513d

ich habe ein MM angelegt "mm_event_specials" mit zwei Attributen - das FE-Panel habe ich der Tabelle tl_calendar_events zugewiesen und ich sehen auch das Icon unter den Event-Items.

Beim Anlegen eines Datensatzes kommt:

```
Fatal error: Uncaught exception ContaoCommunityAlliance\DcGeneral\Exception\DcGeneralRuntimeException with message Unparsable encoded id value: '3' thrown in system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/IdSerializer.php on line 140

#0 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(825): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer::fromSerialized('3')
#1 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1620): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->checkLanguage()
#2 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(996): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), NULL, Object(Closure), Object(Closure))
#3 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->create()
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(162): call_user_func_array(Array, Array)
#5 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#6 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#7 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(120): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#9 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(72): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#10 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(120): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(233): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#12 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/DC_General.php(257): ContaoCommunityAlliance\DcGeneral\DC_General->callAction()
#13 system/modules/core/classes/Backend.php(430): ContaoCommunityAlliance\DcGeneral\DC_General->create()
#14 contao/main.php(136): Contao\Backend->getBackendModule('calendar')
#15 contao/main.php(287): Main->run()
#16 {main}
```

**Comment by xantippe** [comment]
Fehler nur (noch) bei bestimmten Contao-Tabellen https://github.com/contao-community-alliance/dc-general/issues/179
