### ISSUE TITLE
Speichern eines Items bringt Fehler

### ISSUE THREAD

**Issue by Hauge** [contao-community-alliance/dc-general#77]
dev-develop @ 6312da    2014-09-24 22:53:54
Speichern und Schließen funktioniert.
Bei Klick auf Speichern kommt:
```
Recoverable error: Argument 1 passed to ContaoCommunityAlliance\Contao\Bindings\Subscribers\BackendSubscriber::handleAddToUrl() must be an instance of ContaoCommunityAlliance\Contao\Bindings\Events\Backend\AddToUrlEvent, instance of ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent given in system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/BackendSubscriber.php on line 47

#0 system/modules/events-contao-bindings/classes/src/ContaoCommunityAlliance/Contao/Bindings/Subscribers/BackendSubscriber.php(47): __error(4096, 'Argument 1 pass...', '/var/www/client...', 47, Array)
#1 [internal function]: ContaoCommunityAlliance\Contao\Bindings\Subscribers\BackendSubscriber->handleAddToUrl(Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent), 'contao.events.b...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#2 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent), 'contao.events.b...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'contao.events.b...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent))
#4 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(116): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('contao.events.b...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent))
#5 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(69): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('contao.events.b...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent))
#6 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(501): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('contao.events.b...', Object(ContaoCommunityAlliance\Contao\Bindings\Events\Controller\AddToUrlEvent))
#7 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/EditMask.php(686): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->handleSubmit(Object(MetaModels\DcGeneral\Data\Model))
#8 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1317): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\EditMask->execute()
#9 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(1290): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->createEditMask(Object(MetaModels\DcGeneral\Data\Model), Object(MetaModels\DcGeneral\Data\Model), NULL, NULL)
#10 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->edit()
#11 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(155): call_user_func_array(Array, Array)
#12 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#13 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#14 system/modules/symfony-event-dispatcher/classes/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#15 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(116): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#16 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Event/EventPropagator.php(69): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#17 system/modules/dc-general/classes/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(124): ContaoCommunityAlliance\DcGeneral\Event\EventPropagator->propagate('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), Array)
#18 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(238): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#19 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(263): MetaModels\BackendIntegration\Module->runDC()
#20 system/modules/metamodels/classes/src/MetaModels/BackendIntegration/Module.php(283): MetaModels\BackendIntegration\Module->performNormal()
#21 system/modules/core/classes/Backend.php(409): MetaModels\BackendIntegration\Module->generate()
#22 contao/main.php(142): Contao\Backend->getBackendModule('metamodel_mm_ta...')
#23 contao/main.php(293): Main->run()
#24 {main}


```

**Comment by discordier** [comment]
Ich kann das Problem nicht reproduzieren. An den entsprechenden Codestellen hat sich jedoch etliches getan, also ist es hoffentlich behoben.
Sollte es erneut auftreten, dann bitte neues ticket.
