### ISSUE TITLE
No sorting property defined

### ISSUE THREAD

**Issue by psren** [contao-community-alliance/dc-general#93]
habe ich was übersehen was ich definieren muss? Ich glaube irgendwie nicht, bin mir aber nicht sicher.

```php
Fatal error: Uncaught exception RuntimeException with message No sorting property defined for mm_tags thrown in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php on line 357
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/SortingManager.php(175): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->calculate()
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(1066): ContaoCommunityAlliance\DcGeneral\Controller\SortingManager->getResults()
#2 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(941): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->pasteTop(Object(ContaoCommunityAlliance\DcGeneral\Data\DefaultCollection), NULL, NULL)
#3 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(766): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->sortAndPersistModels(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#4 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(642): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->doActions(Array, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, Array)
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(505): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->applyClipboardActions(NULL, NULL, Object(ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\IdSerializer), NULL, NULL, Array)
#6 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/TreeView.php(546): ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\TreeView->paste(Object(ContaoCommunityAlliance\DcGeneral\Action))
#8 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#9 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#11 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#13 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#14 system/modules/core/classes/Backend.php(406): MetaModels\BackendIntegration\Module->generate()
#15 system/modules/core/controllers/BackendMain.php(126): Contao\Backend->getBackendModule('metamodel_mm_ta...')
#16 contao/main.php(20): Contao\BackendMain->run()
#17 {main}
```

**Comment by dmolineus** [comment]
Does it still occur? Probably fixed during fixes in the last months. For example https://github.com/MetaModels/core/commit/4bcb7e1249738776643ffa2d4ee924518d370d3b addressed an issue with missing sorting property.

Please test it again and report if it's working now.

**Comment by asaage** [comment]
MetaModels/core@4bcb7e1 fixed it.
But somehow that is missing in the latest [nightly](https://now.metamodel.me/de/home?file=files/nightlies/nightly-tng.zip).
Can somebody tell on what occasions those are built? Probably once a night or on every new commit?

**Comment by discordier** [comment]
Should be every hour. I will have a look on it.
