### ISSUE TITLE
must be an instance of ContaoCommunityAlliance\DcGeneral\Data\ModelInterface

### ISSUE THREAD

**Issue by psren** [contao-community-alliance/dc-general#98]
If i click on the icon to get the list of my items in the MetaModel I'm getting the following error.

```php
Recoverable error: Argument 2 passed to ContaoCommunityAlliance\DcGeneral\Event\AbstractModelAwareEvent::__construct() must be an instance of ContaoCommunityAlliance\DcGeneral\Data\ModelInterface, null given, called in /kunden/302047_70174/kunden/reich/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php on line 226 and defined in composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/AbstractModelAwareEvent.php on line 43
#0 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Event/AbstractModelAwareEvent.php(43): __error(4096, 'Argument 2 pass...', '/kunden/302047_...', 43, Array)
#1 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/Controller/ClipboardController.php(226): ContaoCommunityAlliance\DcGeneral\Event\AbstractModelAwareEvent->__construct(Object(ContaoCommunityAlliance\DcGeneral\DefaultEnvironment), NULL)
#2 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\Controller\ClipboardController->handleView(Object(ContaoCommunityAlliance\DcGeneral\Event\ViewEvent), 'dc-general.view', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#3 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ViewEvent), 'dc-general.view', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#4 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.view', Object(ContaoCommunityAlliance\DcGeneral\Event\ViewEvent))
#5 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/ListView.php(320): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.view', Object(ContaoCommunityAlliance\DcGeneral\Event\ViewEvent))
#6 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\ListView->showAll(Object(ContaoCommunityAlliance\DcGeneral\Action))
#7 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/View/Contao2BackendView/BaseView.php(138): call_user_func_array(Array, Array)
#8 [internal function]: ContaoCommunityAlliance\DcGeneral\Contao\View\Contao2BackendView\BaseView->handleAction(Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#9 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(164): call_user_func(Array, Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent), 'dc-general.acti...', Object(Symfony\Component\EventDispatcher\EventDispatcher))
#10 composer/vendor/symfony/event-dispatcher/Symfony/Component/EventDispatcher/EventDispatcher.php(53): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch(Array, 'dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#11 composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Controller/DefaultController.php(115): Symfony\Component\EventDispatcher\EventDispatcher->dispatch('dc-general.acti...', Object(ContaoCommunityAlliance\DcGeneral\Event\ActionEvent))
#12 composer/vendor/metamodels/core/src/MetaModels/BackendIntegration/Module.php(77): ContaoCommunityAlliance\DcGeneral\Controller\DefaultController->handle(Object(ContaoCommunityAlliance\DcGeneral\Action))
#13 system/modules/core/classes/Backend.php(262): MetaModels\BackendIntegration\Module->generate()
#14 contao/main.php(137): Contao\Backend->getBackendModule('metamodel_mm_ta...')
#15 contao/main.php(288): Main->run()
#16 {main}

Fatal error: Call to a member function getProviderName() on null in /kunden/302047_70174/kunden/reich/composer/vendor/contao-community-alliance/dc-general/src/ContaoCommunityAlliance/DcGeneral/Contao/Subscriber/FormatModelLabelSubscriber.php on line 47
```

**Comment by psren** [comment]
Das ganze tritt auf wenn man ein MM anlegt dass eine Tabelle nutzt die von einem anderen (jetzt gelöschten) MM genutzt wurde. Kann sein dass das ein Cache-Problem war.

**Comment by discordier** [comment]
Danke, dann myssen wir das noch besser abfangen.

**Comment by discordier** [comment]
@psren kannst du bitte nochmal testen? in `2.0.0-beta26` sollte das Problem behoben sein.

**Comment by psren** [comment]
Ja, sieht gut aus.
